Spring:
  datasource:
    name: saltmerch
    platform: postgres
    url: jdbc:postgresql://localhost:5432/saltmerch
    username: jensenyh
    password: password
    port: 5432:5432

server:
  port: 8099
  servlet:
    contextPath: /api/v1/



